#服务配置
server:
  port: 8088
  context-path: /

#freemarke配置
spring:
 thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
 freemarker:
  cache: false
  checkTemplateLocation: true
  contentType: text/html
  suffix: .ftl
  templateEncoding: UTF-8
  templateLoaderPath: classpath:/templates/
  settings:
   number_format: 0.##
 datasource:
  url: jdbc:mysql://47.105.168.142:3306/crm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
  username: root
  password: 123456
  driverClassName: com.mysql.jdbc.Driver
  max-active: 20
  max-idle: 8
  min-idle: 8
  initial-size: 10
 http:
  multipart:
   maxFileSize: 10Mb
   maxRequestSize: 10Mb

#Mybatis Plus
mybatis-plus:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*/*/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.xxx.model.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #    logic-delete-value: 1
    #    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #metaObjectHandler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#配置路径
path:
 basepackage: com.xxx.model
 outRoot: H:\workspace\crm
 #baseUrl: H:\workspace\crm\src\main\webapp\
 baseUrl: /usr/tomcat/apache-tomcat-8.5.35/webapps/crm